In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
data=pd.read_csv('winequality-red.csv')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
data.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [4]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1:]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=0)

In [6]:
x_train.shape

(1279, 11)

In [7]:
y_train.shape

(1279, 1)

In [8]:
x_test.shape

(320, 11)

In [9]:
y_test.shape

(320, 1)

# Feature scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

# LogisticRegression

In [11]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Users\hp\anaconda3\envs\new_env\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [12]:
y_pred=classifier.predict(x_test)
y_pred

array([6, 5, 7, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 7, 7, 6, 6, 5, 6, 5,
       6, 7, 5, 5, 5, 6, 5, 7, 6, 6, 6, 5, 6, 6, 5, 6, 7, 6, 5, 6, 7, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 6, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 7, 5,
       5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 6, 7, 5, 5, 6, 7, 5, 5,
       6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 6, 5, 6, 6, 5, 6,
       6, 5, 5, 5, 6, 6, 6, 6, 7, 5, 6, 5, 6, 7, 5, 6, 6, 5, 5, 7, 6, 6,
       7, 7, 6, 5, 5, 7, 5, 6, 7, 5, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 7, 5, 5, 6, 6, 6, 5,
       5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 7, 7, 6, 5, 5,
       5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6,
       5, 5, 5, 5, 6, 7, 5, 6, 5, 6, 6, 6, 6, 5, 7, 6, 5, 7, 6, 7, 6, 5,
       5, 5, 7, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6,

# Handle imbalance (SMOTE)

In [14]:
from imblearn.combine import SMOTETomek
sm=SMOTETomek()
x_res,y_res=sm.fit_resample(x_train,y_train)
y_res

quality
0           5
1           5
2           5
3           8
4           6
...       ...
3195        8
3196        8
3197        8
3198        8
3199        8

[3200 rows x 1 columns]

In [15]:

print("before balancing :",y.shape)
print("After Balancing  :",y_res.shape)

before balancing : (1599, 1)
After Balancing  : (3200, 1)


# Apply LDA

In [16]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
X_train_lda = lda.fit_transform(x_train, y_train)

C:\Users\hp\anaconda3\envs\new_env\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
y_pred_lda=lda.predict(x_test)
y_pred_lda

array([6, 5, 7, 5, 6, 5, 5, 6, 4, 5, 5, 5, 6, 4, 6, 7, 7, 6, 6, 5, 7, 5,
       6, 7, 5, 5, 5, 7, 5, 7, 6, 6, 6, 5, 6, 6, 5, 6, 7, 6, 5, 6, 7, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 6, 7, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 6, 7, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 7, 5,
       5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 8, 7, 5, 5, 6, 7, 5, 5,
       6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 6, 5, 6, 6, 5, 6,
       6, 5, 5, 5, 6, 6, 6, 6, 7, 5, 6, 5, 6, 7, 5, 6, 6, 5, 5, 7, 6, 6,
       7, 7, 6, 5, 5, 7, 5, 6, 7, 5, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 7, 6, 5, 6, 5, 5, 7, 5, 6, 6, 6, 6, 5,
       5, 6, 7, 6, 5, 6, 7, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 7, 7, 6, 5, 5,
       5, 5, 6, 5, 5, 5, 3, 7, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6,
       5, 5, 5, 5, 6, 7, 5, 6, 5, 6, 6, 6, 7, 5, 7, 7, 5, 7, 6, 7, 6, 5,
       5, 5, 7, 6, 6, 4, 6, 5, 5, 6, 5, 5, 5, 5, 6,

# Apply PCA

In [18]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(x_train)

In [19]:
y_pred_pca=lda.predict(x_test)
y_pred_pca

array([6, 5, 7, 5, 6, 5, 5, 6, 4, 5, 5, 5, 6, 4, 6, 7, 7, 6, 6, 5, 7, 5,
       6, 7, 5, 5, 5, 7, 5, 7, 6, 6, 6, 5, 6, 6, 5, 6, 7, 6, 5, 6, 7, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 6, 7, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 6, 7, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 7, 5,
       5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 8, 7, 5, 5, 6, 7, 5, 5,
       6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 6, 5, 6, 6, 5, 6,
       6, 5, 5, 5, 6, 6, 6, 6, 7, 5, 6, 5, 6, 7, 5, 6, 6, 5, 5, 7, 6, 6,
       7, 7, 6, 5, 5, 7, 5, 6, 7, 5, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 7, 6, 5, 6, 5, 5, 7, 5, 6, 6, 6, 6, 5,
       5, 6, 7, 6, 5, 6, 7, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 7, 7, 6, 5, 5,
       5, 5, 6, 5, 5, 5, 3, 7, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6,
       5, 5, 5, 5, 6, 7, 5, 6, 5, 6, 6, 6, 7, 5, 7, 7, 5, 7, 6, 7, 6, 5,
       5, 5, 7, 6, 6, 4, 6, 5, 5, 6, 5, 5, 5, 5, 6,

# RandomForestClassifier

In [20]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(x_res,y_res)

C:\Users\hp\anaconda3\envs\new_env\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=0)

In [21]:
y_pred_res=rf.predict(x_res)
y_pred_res

array([5, 5, 5, ..., 8, 8, 8], dtype=int64)

# GridSearchCV

In [25]:
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_search = GridSearchCV(rf, param_grid, cv=5, n_jobs=-1)

grid_search.fit(x_res, y_res)

C:\Users\hp\anaconda3\envs\new_env\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=0), n_jobs=-1,
             param_grid={'max_depth': [None, 10], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]})

# RandomizedSearchCV

In [26]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

# Define the parameter distribution
param_dist = {
    'n_estimators': randint(50, 150),  # Randomly sample values between 50 and 150
    'max_depth': [None, 10, 20],
    'min_samples_split': randint(2, 10),  # Randomly sample values between 2 and 10
    'min_samples_leaf': randint(1, 4)  # Randomly sample values between 1 and 4
}

# Create a RandomizedSearchCV instance
random_search = RandomizedSearchCV(rf, param_distributions=param_dist, n_iter=10, cv=5, n_jobs=-1)

# Fit the model
random_search.fit(x_res, y_res)

# Print the best hyperparameters
print("Best Hyperparameters:", random_search.best_params_)

C:\Users\hp\anaconda3\envs\new_env\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Best Hyperparameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 124}


# Cross-validation

In [28]:
cv_scores = cross_val_score(rf, x_res, y_res, cv=5, n_jobs=-1)

# Model evaluation

In [31]:
from sklearn.metrics import accuracy_score
best_rf = grid_search.best_estimator_
y_pred = best_rf.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)

In [33]:
print("LDA transformed data shape:", X_train_lda.shape)
print("PCA transformed data shape:", X_train_pca.shape)
print("Grid Search Best Parameters:", grid_search.best_params_)
print("Randomized Search Best Parameters:", random_search.best_params_)
print("Cross-Validation Scores:", cv_scores)
print("Accuracy on Test Set:", accuracy)

LDA transformed data shape: (1279, 5)
PCA transformed data shape: (1279, 2)
Grid Search Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}
Randomized Search Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 124}
Cross-Validation Scores: [0.86875   0.875     0.8921875 0.8875    0.9140625]
Accuracy on Test Set: 0.646875
