In [2]:
import numpy as np

In [6]:
np_olympic_country=np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold=np.array([29, 38, 24, 46, 13,7,11])

np_olympic_country_silver=np.array([17,18,25,28,8,14,11])
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])

# 1.find the country index with maximum gold

In [9]:
g=np_olympic_country_gold.argmax()
index=np_olympic_country[g]
index

'US'

# 2. Print Country with Maximum gold

In [10]:
print(index,"with maximum gold is",max(np_olympic_country_gold))

US with maximum gold is  46


# 3. Find countries with more than 20 gold medals

In [26]:
s=np_olympic_country_gold
print("The countries with more than 20 gold medals are :")
for i in range(len(s)):
    if s[i] > 20:
        print(np_olympic_country[i],end=" ")

The countries with more than 20 gold medals are :
GBR Chine RUS US 

# 4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals

2. print each country nale with total number of medals

In [29]:
s=np_olympic_country_gold
total_medals=np_olympic_country_gold+np_olympic_country_silver+np_olympic_country_Bronze

for i in range(len(s)):
    print(np_olympic_country[i],"with number of gold medals is :",np_olympic_country_gold[i])
    
print()

for i in range(len(total_medals)):
    print(np_olympic_country[i],"number of medals is ",total_medals[i])


[ 65  78  81 103  28  38  36]
GBR with number of gold medals is : 29
Chine with number of gold medals is : 38
RUS with number of gold medals is : 24
US with number of gold medals is : 46
KOR with number of gold medals is : 13
JPN with number of gold medals is : 7
GER with number of gold medals is : 11

GBR number of medals is  65
Chine number of medals is  78
RUS number of medals is  81
US number of medals is  103
KOR number of medals is  28
JPN number of medals is  38
GER number of medals is  36


# 1. Create a 3x3x3 array with random values

In [34]:
import numpy as np
array=np.random.rand(3,3,3)
print(array)

[[[0.05958613 0.37009717 0.30448015]
  [0.70451193 0.06937221 0.27495331]
  [0.44134608 0.08033637 0.07635778]]

 [[0.62708797 0.3455411  0.66097612]
  [0.0723849  0.36194362 0.97569194]
  [0.46004173 0.69329777 0.74228879]]

 [[0.80623955 0.37982381 0.17712847]
  [0.6819584  0.46875022 0.10803028]
  [0.06609513 0.21207519 0.15810219]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
s=np.array([0,1,2,3,4])
d=np.diag(s)
d

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [57]:
arr=np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [61]:
arr=np.random.rand(5,5)
min_value=arr.min()
max_value=arr.max()
normalized=(arr - min_value )/(max_value-min_value)
print("origina array")
print()
print(arr)
print()
print("normalised array")
print()
print(normalized)

origina array

[[0.32113112 0.78228339 0.0251196  0.47487472 0.18780274]
 [0.28783818 0.37588327 0.11031315 0.10132878 0.86459602]
 [0.83695608 0.19077085 0.86045921 0.99510001 0.30409469]
 [0.23732062 0.31208476 0.53620434 0.28657978 0.95246705]
 [0.55005671 0.37415753 0.15285593 0.38423242 0.63201231]]

normalised array

[[0.30517268 0.78059699 0.         0.46367444 0.16771797]
 [0.27084937 0.36161933 0.08783018 0.07856775 0.86545709]
 [0.83696173 0.17077793 0.86119225 1.         0.28760899]
 [0.21876835 0.29584635 0.52690212 0.26955202 0.95604761]
 [0.54118321 0.35984018 0.13168959 0.37022688 0.62567523]]


# 5. How to find common values between two arrays?

In [63]:
a1=np.array([1,2,3,4,5])
a2=np.array([1,2,7,4,3])
a3=np.intersect1d(a1,a2)
print("the common values from both arrays is ",a3)

the common values from both arrays is  [1 2 3 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [64]:
from datetime import date,timedelta
today=date.today()
yesterday=today-timedelta(1)
tommorow=today+timedelta(1)
print(today," ",yesterday," ",tommorow," ")

2023-09-21   2023-09-20   2023-09-22  


# 7. Consider two random array A and B, check if they are equal

In [71]:
a1=np.random.rand(4,4)
a2=np.random.rand(4,4)
equal=np.array_equal(a1,a2)

print("Array 1:")
print()
print(a1)
print()
print("second array")
print()
print(a2)
print()
print("the both arrays equal or not")

print(equal)

Array 1:

[[0.63197242 0.59729129 0.29916322 0.28269942]
 [0.28607424 0.20844638 0.78812132 0.8198945 ]
 [0.30112282 0.14139338 0.86525836 0.60324383]
 [0.04399624 0.48741815 0.3907854  0.50200282]]

second array

[[0.82948034 0.09124199 0.45503393 0.71228872]
 [0.78172123 0.52698033 0.60052656 0.20382116]
 [0.35631705 0.50296198 0.37317434 0.46553206]
 [0.75882068 0.72249727 0.34372481 0.57306014]]

the both arrays equal or not
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [81]:
vec=np.random.rand(10)
print("original vector\n",vec)

vec[vec.argmax()]=0
print()
print("the maximum value replace with 0")
print(vec)

original vector
 [0.22508049 0.92108214 0.51716001 0.11244738 0.82612974 0.5541129
 0.86430726 0.04074603 0.5588993  0.83926498]

the maximum value replace with 0
[0.22508049 0.         0.51716001 0.11244738 0.82612974 0.5541129
 0.86430726 0.04074603 0.5588993  0.83926498]


# 9. How to print all the values of an array?

In [82]:
import numpy as np


array = np.array([[2,3,4], [6,7,8], [2,5,7]])


print(array)


[[2 3 4]
 [6 7 8]
 [2 5 7]]


# 10.Subtract the mean of each row of a matrix

In [85]:
import numpy as np

# Create a sample matrix
matrix = np.array([[2,3,4], 
                   [6,7,2], 
                   [9,1,2]])


row_means = matrix.mean(axis=1)


centered_matrix = matrix - row_means

print("Original matrix:")
print(matrix)
print("\nCentered matrix:")
print(centered_matrix)


Original matrix:
[[2 3 4]
 [6 7 2]
 [9 1 2]]

Centered matrix:
[[-1. -2.  0.]
 [ 3.  2. -2.]
 [ 6. -4. -2.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated Indices)?

In [87]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])


indices = np.array([1, 1, 2, 2, 2])

for index in indices:
    vector[index] += 1

print(vector)


[1 4 6 4 5]


# 12.How to get the diagonal of a dot product?

In [96]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 1], [0, 3]])

c=np.dot(A,B)
print(c)
diag=np.diagonal(c)
print("The diagonal is :",diag)

[[ 2  7]
 [ 6 15]]
The diagonal is : [ 2 15]


# 13.How to find the most frequent value in an array?

In [104]:
a=np.random.randint(1,10,50)
most_frequent = np.bincount(a).argmax()
print(a)
print("The most frequent value in an array : ",most_frequent)

[5 6 9 1 5 6 3 3 5 2 3 5 2 3 2 8 9 1 2 5 9 5 7 8 9 7 2 6 7 1 6 1 1 5 3 6 9
 8 6 6 9 6 1 3 7 6 4 6 8 3]
The most frequent value in an array :  6


# 14.How to get the n largest values of an array

In [106]:
import numpy as np

# Sample array for demonstration
a = np.array([1, 5, 7, 2, 8, 3, 9, 4, 6])

# Define n (e.g., n=3 for the 3 largest values)
n = 4

# Get the n largest values
n_largest_values = np.partition(a, -n)[-n:]
n_largest_values_sorted = np.sort(n_largest_values)

print("Original array:", a)
print(f"{n} largest values:", n_largest_values_sorted)


Original array: [1 5 7 2 8 3 9 4 6]
4 largest values: [6 7 8 9]


# 15.How to create a record array from a regular array?

In [108]:
import numpy as np

# Data for the record array
data = [(1, 'First', 0.5),
        (2, 'Second', 1.3),
        (3, 'Third', 0.8)]

# Define the dtype for the record array
dtype = [('id', int), ('name', 'U10'), ('value', float)]

# Create the record array
record_array = np.array(data, dtype=dtype)

print(record_array)

# Accessing fields in record array
print(record_array[0]['name'])  
print(record_array[1]['value'])  


[(1, 'First', 0.5) (2, 'Second', 1.3) (3, 'Third', 0.8)]
First
1.3


# 16. How to swap two rows of an array?

In [119]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr)
print()
arr[[0,1]]=arr[[1,0]]

print("after swapping")

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

after swapping
[[4 5 6]
 [1 2 3]
 [7 8 9]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [123]:
x=np.array([[23,34,121],[23,22,67],[686,434,123]])
y=x.reshape(2,4,4)
print(y)

ValueError: cannot reshape array of size 9 into shape (2,4,4)